### PR TITLE
Update docker-compose.yml job-lite-2.12.1

### PR DESCRIPTION
**Pull request by 0xbase12**
Update job engine to latest

### CODE REVIEW

**Comment by cjdcordeiro** [comment]
@0xbase12 do you need it released now? or can it wait?

**Comment by 0xbase12** [comment]
Yes please

**Comment by cjdcordeiro** [comment]
@0xbase12 
the tests are failing:
> manifest for nuvla/job-lite:2.12.2 not found: manifest unknown: manifest unknown

is this update for 2.12.2 or 2.12.1?

**Comment by 0xbase12** [comment]
Oh It should be the last release 2.12.2. 
It should exist on docker hub:https://hub.docker.com/repository/docker/nuvla/job-lite

Bad pull request branch/name sorry

**Comment by cjdcordeiro** [comment]
np. But that doesn't exist in fact.

Maybe you meant 2.14.2?

**Comment by 0xbase12** [comment]
Aiieeeee aie aie, too complex pull request 🤦

**Comment by cjdcordeiro** [comment]
image

**Comment by cjdcordeiro** [comment]
:p can you re-submit the PR?

**Pull request merged**
